### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by kiokumicu** [Zewo/OpenSSL#3]
When I'n trying compiling project on linux, using swift development snapshot from February 8, 2016, I got error
```
Compiling Swift Module 'OpenSSL' (15 sources)
/mnt/swift/ZewoTest/Packages/OpenSSL-0.2.3/Source/Method.swift:57:11: error: use of unresolved identifier 'SSLv3_method'
                        return SSLv3_method()
                               ^~~~~~~~~~~~
/mnt/swift/ZewoTest/Packages/OpenSSL-0.2.3/Source/Method.swift:59:11: error: use of unresolved identifier 'SSLv3_server_method'
                        return SSLv3_server_method()
                               ^~~~~~~~~~~~~~~~~~~
/mnt/swift/ZewoTest/Packages/OpenSSL-0.2.3/Source/Method.swift:61:11: error: use of unresolved identifier 'SSLv3_client_method'
                        return SSLv3_client_method()
                               ^~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/usr/bin/swift-build-tool", "-f", "/mnt/swift/ZewoTest/.build/debug/OpenSSL.o/llbuild.yaml"]
```

**Comment by paulofaria** [comment]
You should install Zewo dependencies. Follow guide at docs.zewo.io.

OS X:
```sh
brew tap zewo/tap
brew install zewo
```

Linux:
```sh
echo "deb [trusted=yes] http://apt.zewo.io/deb ./" | sudo tee --append /etc/apt/sources.list
sudo apt-get update
sudo apt-get install zewo
```

**Comment by kiokumicu** [comment]
Already installed latest version of Zewo package

**Comment by kiokumicu** [comment]
I guess it's problem with Debian (. In Ubuntu work fine.

**Comment by Danappelxx** [comment]
That's strange. Are there OpenSSL api changes between ubuntu/debian? Wouldn't make much sense... Try upgrading your openssl version on debian and see if that fixes it.

**Comment by Danappelxx** [comment]
Actually, before you do that, what version of OpenSSL do you have on Debian (and Ubuntu)? Just for future reference in case that is the issue.

**Comment by kiokumicu** [comment]
Debian - OpenSSL 1.0.2e 3 Dec 2015 (Library: OpenSSL 1.0.2f  28 Jan 2016)
Ubuntu - OpenSSL 1.0.1f 6 Jan 2014

**Comment by Danappelxx** [comment]
Looks like OpenSSL on Debian is compiled with some methods specifically disabled ([not-very-reliable-source-here](https://news.ycombinator.com/item?id=9439491)). I suppose you can recompile OpenSSL without those flags but in the long-term I'm not sure what to do about this.

@paulofaria @alex-alex this is your specialty I believe :)

**Comment by kiokumicu** [comment]
Maybe remove SSLv3 support ?)

**Comment by kiokumicu** [comment]
So what about remove SSLv3 support ?

**Comment by paulofaria** [comment]
I'll take a look.

**Comment by paulofaria** [comment]
I now removed SSLv3 support. Please do `rm -rf Packages/` and `swift build` again.

**Comment by kiokumicu** [comment]
It's work! Thx!

**Comment by paulofaria** [comment]
awesome! :rocket:
